version: '3'

services:
  test_project:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./testapp:/testapp
    environment:
      - FLASK_DEBUG=1
      - DEBUG=1
      - FLASK_APP=/testapp/main.py
    command: /testapp/run.sh
    restart: "no"
